httping: fix build with NLS
v2: INTL support was not at default DEPENDS (broke nossl)

libintl.h was not found when CONFIG_BUILD_NLS was selected
explicit -lintl fixes
undefined reference to `libintl_gettext'

fixes ticket #15816

Signed-off-by: Dirk Neukirchen <dirkneukirchen@web.de>
Signed-off-by: Florian Fainelli <florian@openwrt.org>